# Generated by Django 5.0.2 on 2024-02-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmonsaraf',
            old_name='عصير_جاف',
            new_name='عصير',
        ),
        migrations.RenameField(
            model_name='taskmortgaa',
            old_name='عصير_جاف',
            new_name='عصير',
        ),
        migrations.RenameField(
            model_name='tazamonsaraf',
            old_name='عصير_جاف',
            new_name='عصير',
        ),
        migrations.RenameField(
            model_name='tazatayyen',
            old_name='عصير_جاف',
            new_name='عصير',
        ),
    ]
