# Generated by Django 5.0.2 on 2024-02-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_rename_عصير_جاف_taskmonsaraf_عصير_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmonsaraf',
            old_name='عصير',
            new_name='عصير_حاف',
        ),
        migrations.RenameField(
            model_name='taskmortgaa',
            old_name='عصير',
            new_name='عصير_حاف',
        ),
        migrations.RenameField(
            model_name='tazamonsaraf',
            old_name='عصير',
            new_name='عصير_حاف',
        ),
        migrations.RenameField(
            model_name='tazatayyen',
            old_name='عصير',
            new_name='عصير_حاف',
        ),
        migrations.AlterField(
            model_name='product',
            name='addition_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ اضافة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='azen',
            field=models.IntegerField(default=0, verbose_name='رقم الاذن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.productmetadata', verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='member',
            field=models.CharField(max_length=50, verbose_name='نوع التعيين'),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='taayeen_season',
            field=models.CharField(max_length=50, verbose_name='الموسم'),
        ),
    ]
