# Generated by Django 5.0.2 on 2024-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_rename_عصير_taskmonsaraf_عصير_حاف_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='date',
            field=models.DateField(verbose_name='تاريخ الصرف'),
        ),
    ]
