# Generated by Django 5.0.2 on 2024-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_alter_tazamonsaraf_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='addition_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AlterField(
            model_name='tarfehmonsaraf',
            name='date',
            field=models.DateField(verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='taskmonsaraf',
            name='date',
            field=models.DateField(verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='taskmortgaa',
            name='date',
            field=models.DateField(),
        ),
    ]
