# Generated by Django 5.0.2 on 2024-02-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_remove_product_addition_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmortgaa',
            old_name='عصير_حاف',
            new_name='عصير_جاف',
        ),
    ]
