# Generated by Django 5.0.2 on 2024-02-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_rename_عصير_حاف_taskmortgaa_عصير_جاف'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmonsaraf',
            old_name='عصير_حاف',
            new_name='عصير_جاف',
        ),
        migrations.RenameField(
            model_name='tazamonsaraf',
            old_name='عصير_حاف',
            new_name='عصير_جاف',
        ),
        migrations.RenameField(
            model_name='tazatayyen',
            old_name='عصير_حاف',
            new_name='عصير_جاف',
        ),
    ]
