# Generated by Django 5.0.2 on 2024-02-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_alter_product_quantity_alter_tarfehmonsaraf_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='الكمية'),
        ),
    ]
