# Generated by Django 5.0.2 on 2024-02-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0010_alter_tarfehmonsaraf_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmonsaraf',
            name='members',
            field=models.JSONField(default=list),
        ),
    ]
