# Generated by Django 5.0.2 on 2024-02-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0011_taskmonsaraf_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmonsaraf',
            name='members',
            field=models.JSONField(default=list, verbose_name='اعضاء المأمورية'),
        ),
    ]
