# Generated by Django 5.0.2 on 2024-02-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0012_alter_taskmonsaraf_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='tarfehmonsaraf',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='المقرر'),
        ),
        migrations.AlterField(
            model_name='taskmonsaraf',
            name='فول_معلب_360_جرام_العلبة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='taskmortgaa',
            name='فول_معلب_360_جرام_العلبة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='ارز_بلدى',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='بصل_ناشف',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='بهارات',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='بيض',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='ثوم',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='جبنة_بيضاء_80جم',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='حلاوة_قطع',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='خبز',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='خضار_مجمد',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='دواجن_مجمده',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='زبادى',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='زيت_طعام',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='سكر_باكيت',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='سلاطه',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='شاى_فتلة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='شعرية',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='صلصة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='عدس',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='فاصوليا_جافة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='فاكهه',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='فلفل_اسود',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='فول_صحيح',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='فول_معلب_360_جرام_العلبة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='كمون_حصى',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='لحوم_مجمده',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='مربى_قطع',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='مكرونة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazamonsaraf',
            name='ملح_طعام',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='ارز_بلدى',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='بصل_ناشف',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='بهارات',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='بيض',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='ثوم',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='جبنة_بيضاء_80جم',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='حلاوة_قطع',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='خبز',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='خضار_مجمد',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='دواجن_مجمده',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='زبادى',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='زيت_طعام',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='سكر_باكيت',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='سلاطه',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='شاى_فتلة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='شعرية',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='صلصة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='عدس',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='فاصوليا_جافة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='فاكهه',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='فلفل_اسود',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='فول_صحيح',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='فول_معلب_360_جرام_العلبة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='كمون_حصى',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='لحوم_مجمده',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='مربى_قطع',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='مكرونة',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tazatayyen',
            name='ملح_طعام',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
