# Generated by Django 5.0.2 on 2024-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0013_alter_product_quantity_alter_tarfehmonsaraf_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmonsaraf',
            name='members',
        ),
        migrations.AddField(
            model_name='taskmonsaraf',
            name='members',
            field=models.ManyToManyField(to='POS.member', verbose_name='أعضاء المأمورية'),
        ),
    ]
