# Generated by Django 5.0.2 on 2024-02-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0014_member_remove_taskmonsaraf_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmonsaraf',
            name='members',
        ),
    ]
