# Generated by Django 5.0.2 on 2024-02-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0015_remove_taskmonsaraf_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmonsaraf',
            name='members',
            field=models.ManyToManyField(to='POS.member', verbose_name='أعضاء المأمورية'),
        ),
    ]
