# Generated by Django 4.1.4 on 2024-02-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_initial'),
        ('POS', '0018_alter_member_options_alter_product_options_and_more'),
    ]

    operations = [
    ]
